[package]
name = "webp-animation"
version = "0.1.0"
authors = ["Mika Vatanen <blaind@blaind.net>"]
edition = "2018"

[dependencies]
image = { version = "0.23.14", optional = true }

[dependencies.libwebp-sys2]
git = "https://github.com/blaind/libwebp-sys2-rs"
features = ["0_5", "demux", "mux"]
rev = "d0daaff"

[dev-dependencies]
image = { version = "0.23.14" }
imageproc = { version = "0.22.0" }
